### PR TITLE
[MIG] hotel_housekeeping: Migration to 11.0

### PR DESCRIPTION
**Pull request by KrishnaPrajapati-SerpentCS**

### CODE REVIEW

**Comment by omarouhari** [comment]
what remains to be done in migration and how can we validate changes?

**Comment by JayVora-SerpentCS** [comment]
@omarouhari Every bit has to be checked on review. You may propose a review or contribute.

**Comment by omarouhari** [comment]
How can I do that and how can I accelerate the check of every bit ?

**Comment by pedrobaeza** [comment]
See https://odoo-community.org/page/review for a brief description

**Comment by serpentcs-dev1** [comment]
Supersedes now with #41

**Pull request closed without merging**
