### PR TITLE
[13.0] [MIG] Hotel

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Hotel Management
================

Module for Complete Hotel management which includes the basic operations at a hotel/apartment.

You can manage:

* Configure Property

* Hotel Configuration

* Manage history of Check In, Check out

* Manage Folio

* Payment

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@JayVora-SerpentCS Can you please review it?

**Comment by JayVora-SerpentCS** [comment]
@gurneyalex please guide for travis.

**Comment by jcchoquet** [comment]
in version 11, i have add the manage by multi company, are you interested for the V13 ?

**Comment by JayVora-SerpentCS** [comment]
@nikul-serpentcs can you manage to see the conflict ?
@jcchoquet you may make a pull request please.
Thanks,

**Comment by JayVora-SerpentCS** [comment]
@jcchoquet you are sending email but it does not allow us to reply you.
You can see https://pypi.org/project/pylint-odoo/ for more info.
Your issue is for the file permission.

**Pull request closed without merging**
