### PR TITLE
[11.0][FIX] Remove branding

### PR DESCRIPTION
**Pull request by tarteo**
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#11modules

"Don't use your company logo or your corporate branding. Using the author and the list of contributors is enough for people to know about your employer/company and contact you."

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think not all images are branded, isn't it?

**Comment by tarteo** [comment]
@pedrobaeza I removed the index.html file in it's entirely (so it will be generated by gen_addon_readme.py). But I can also just remove the logo's and links from the current index.html file. IMO the generated one is better, what is your opinion?

**Comment by pedrobaeza** [comment]
Well, you haven't checked if the icons removed are used in other parts. The manual index.html seems to be better in principle, but it will be overwritten if readme folder exists.

**Comment by tarteo** [comment]
Ok, then I'll just remove the logo's and links

**Comment by tarteo** [comment]
@pedrobaeza the index.html is back.

**Comment by pedrobaeza** [comment]
hotel/static/description/Hotel.png seems still relevant.

**Comment by tarteo** [comment]
Yes, I didn't remove it. I only removed the branding from the bottom and the top:

image

**Comment by pedrobaeza** [comment]
OK, sorry for the noise. GitHub is a bit confusing about that.

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking as this violates OCA rules

**Pull request merged**
