### PR TITLE
[FIX][11.0] house_keeping: Fix an issue to not install module.

### PR DESCRIPTION
**Pull request by Dangar-Serpentcs**
Hotel Housekeeping Management
==========================

Manages Housekeeping Activities and its Process

### CODE REVIEW

**Review by JayVora-SerpentCS — APPROVED** [review]
Once CLA is passed, we will merge

**Review by nikul-serpentcs — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this.

**Comment by pedrobaeza** [comment]
Ah, CLA is pending... so we have to wait.

**Comment by nikul-serpentcs** [comment]
@Dangar-Serpentcs CLA is Done, @pedrobaeza You can move forward.

**Comment by JayVora-SerpentCS** [comment]
I got CLA cleared by Eric - Elicocorp.

**Pull request merged**
