### PR TITLE
[11.0] split files

### PR DESCRIPTION
**Pull request by robinkeunen**
The model and view files have grown up quite long. I split the files following the rule "one model per file", unless a model is short and strongly linked to another.

 I'll squash the commits when the PR is approved.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@robinkeunen thank you for the good work, some conflicts plz

**Comment by JayVora-SerpentCS** [comment]
IMHO, split files - can we start from v12/13?

**Comment by robinkeunen** [comment]
I'd rather not since we will only work on v11.

I'll fix the conflicts.

**Comment by robinkeunen** [comment]
Hi @JayVora-SerpentCS 

As you can see in the last fixups, I very carefully rewrote the changes of https://github.com/OCA/vertical-hotel/pull/100 . I hope that it suits you.

**Comment by robinkeunen** [comment]
Coverage has decreased but I don't think that's an issue.

**Comment by robinkeunen** [comment]
Thanks! It's great to contribute to a project with such reactivity!

**Pull request merged**
