### PR TITLE
[MIG]Migrated hotel module in v11.

### PR DESCRIPTION
**Pull request by KrishnaPrajapati-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You have to keep commit history. Please follow technical part of this migration guide:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by serpentcs-dev1** [comment]
@pedrobaeza Strange, It is showing many conflicts while Preserving the commits for the OCA 10.0 hotel module

I am following this steps : 

`$ git clone https://github.com/OCA/vertical-hotel -b 11.0 hotel `
`$ git checkout -b 11.0-mig-hotel origin/11.0`
`$ git format-patch --keep-subject --stdout origin/11.0..origin/10.0 -- hotel | git am -3 --keep`

cc @KrishnaPrajapati-SerpentCS

**Comment by pedrobaeza** [comment]
That's because previously things hadn't got straight away, and there has been several incorrect merge operations over the code, scrambling the commit history. Now the only solution is to resolve that conflicts one by one until having everything imported.

**Comment by serpentcs-dev1** [comment]
Thought so, checked some of the v10 PR where not clean enough, strange how did they get merged then! Also, the https://github.com/OCA/vertical-hotel/commits/10.0/hotel does not look straight.

Okay thanks, we will fix those now in this PR!

**Pull request closed without merging**
