### PR TITLE
[13.0][IMP]Improved pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by dhruvitaSerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This pre-commit is fixed across all OCA repos. If this improvement is valuable, please propose it to https://github.com/OCA/oca-addons-repo-template

**Comment by JayVora-SerpentCS** [comment]
@dhruvitaSerpentCS can you explain why you needed to edit this? 
Compare with other repo if you think hotel repo's file is old.
Thanks

**Comment by dhruvitaSerpentCS** [comment]
@JayVora-SerpentCS Done these changes to regenerate README.rst files.
Take reference from https://github.com/OCA/maintainer-tools

**Comment by JayVora-SerpentCS** [comment]
I am not the expert yet regarding this file.
Can you help @pedrobaeza if this change is right?
I think the yaml file does not need to mention self repo as Dhruvita did.

**Comment by pedrobaeza** [comment]
Well, I'm seeing that this change force to add another tool to the toolset (with its dependencies), so it hasn't been included in the rest of the repositories. It's not needed at all, as README are regenerated by the bot on merge. And also the problem is that each module requires an extra pre-commit conf, so I would remove it.

**Comment by JayVora-SerpentCS** [comment]
right, @dhruvitaSerpentCS can you simple follow examples of other verticals in v13 and follow logically?
Thanks.

**Pull request closed without merging**
