### PR TITLE
[IMP]Improved hotel module.

### PR DESCRIPTION
**Pull request by KrishnaPrajapati-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please specify improvements list and sign the CLA?

**Comment by JayVora-SerpentCS** [comment]
I've emailed to OCA CLA mail.

**Comment by JayVora-SerpentCS** [comment]
is 157 the runbot id?

**Comment by pedrobaeza** [comment]
Yeah, that's it: https://runbot.odoo-community.org/runbot/repo/github-com-oca-vertical-hotel-157

**Pull request merged**
