### PR TITLE
[12.0][FIX]Fixed issue #82

### PR DESCRIPTION
**Pull request by dhruvitaSerpentCS**

### CODE REVIEW

**Comment by vimalpatelserpentcs** [comment]
#82

**Comment by JayVora-SerpentCS** [comment]
Thank you, can you fix travis for this module please?

**Comment by dhruvitaSerpentCS** [comment]
> Thank you, can you fix travis for this module please?

Fixed Travis. Can you please review and merge it?

**Comment by JayVora-SerpentCS** [comment]
@dhruvitaSerpentCS seems some conflict, pls squash commits into 1 too.

**Pull request closed without merging**
