### PR TITLE
[12.0][MIG] report hotel restaurant

### PR DESCRIPTION
**Pull request by dhruvitaSerpentCS**

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @dhruvitaSerpentCS 

Could you make a rebase to get the new travis changes and could test in runbot?

Regards

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs Please help @dhruvitaSerpentCS do the needful.

**Comment by JayVora-SerpentCS** [comment]
Will merge this when @gurneyalex signals runbot.

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs you need to rebase

**Pull request merged**
