### PR TITLE
[11.0]hotel_reservation: fixed the hotel room reservation summary issue 

### PR DESCRIPTION
**Pull request by vimalpatelserpentcs**

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
Issue #53

**Comment by JayVora-SerpentCS** [comment]
Can you please fix travis errors ?

**Comment by JayVora-SerpentCS** [comment]
@gurneyalex can you help see the runbot ?

**Comment by nikul-serpentcs** [comment]
@vimalpatelserpentcs Fix travis: https://travis-ci.org/OCA/vertical-hotel/jobs/485340840#L594-L620

**Comment by nikul-serpentcs** [comment]
> Can you please fix travis errors ?

@JayVora-SerpentCS Done, Mr. Travis :green_heart:

**Pull request merged**
