### PR TITLE
Odoo v8 Hotel Management

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by max3903** [comment]
@JayVora-SerpentCS can you split the migration and make one pull request per module ? It would be easier to split the tasks and review the PR ?

**Comment by gurneyalex** [comment]
CLA ok

**Comment by gurneyalex** [comment]
needs rebasing

**Comment by angelmoya** [comment]
In Domatix we are working refactoring code, this modules have a lot legacy and deprecated code.

You could check our work on https://github.com/Domatix/vertical-hotel/tree/mig_8.0_hotel, when we finish we will prepare pull request, one per module

**Comment by max3903** [comment]
@amoya-dx can you specify which modules you are migrating and refactoring on this issue #3 ? This way, we don't duplicate migration effort on the same module. Thanks.

**Comment by angelmoya** [comment]
Ok, just do it, at the moment only hotel module, we will announce when start to migrate other module.

**Comment by JayVora-SerpentCS** [comment]
@amoya-dx nice to hear that! We actually have been investing more than 2 months and we are driving this stuff towards Pure Hotel+pos+website level. https://github.com/JayVora-SerpentCS/hotelmgmt_v8
May be, we should plan a roadmap!

**Comment by JayVora-SerpentCS** [comment]
However, following @max3903 's suggestion to reduce complexity... I must close this PR and make a new one!

**Pull request closed without merging**
