### PR TITLE
[11.0][FIX]hotel_restaurant:fixed hotel restaurant installable issue

### PR DESCRIPTION
**Pull request by vimalpatelserpentcs**
Fixed #https://github.com/OCA/vertical-hotel/commit/4c0fcfa2f0e2e13e4594853af47e2fd02e2086af#commitcomment-32691500

### CODE REVIEW

**Comment by evillaizan** [comment]
Hello,

Thanks for the FIX, but, When I try generate report: Activities Reports. That not works:

Captura de pantalla 2019-03-20 a la(s) 14 44 36


Captura de pantalla 2019-03-20 a la(s) 14 44 50

Not apear the message error.

Dow you have documentation for this Hotel modules?

Thanks very much.


Ed.

**Comment by vimalpatelserpentcs** [comment]
@evillaizan, Fixed the issue in this PR #64 , so please look into it

**Comment by evillaizan** [comment]
Hi,

The problem was not solved, the problem still persists. What is the purpose of the report of activities per room?.

Regards,

Edson V.

**Comment by vimalpatelserpentcs** [comment]
Hi @evillaizan,
Activity report Issued has been fixed in this PR #64 but still PR is open so that's reason you have to faced this issue

**Pull request merged**
