### PR TITLE
[16.0][MIG] hotel: Migration to 16.0

### PR DESCRIPTION
**Pull request by norlinhenrik**
I have disabled some code and added this message: `TODO: Fix this code for 16.0`

### CODE REVIEW

**Comment by norlinhenrik** [comment]
Hello @JayVora-SerpentCS
I write to you since your company seems to be the main contributor.
I would like to rename some models and fields, e.g.

- hotel.services -> hotel.service (singular name)
- room_categ_id -> type_id (the related model is hotel.room.type)

**Comment by norlinhenrik** [comment]
Models to rename:

- hotel.room.amenities -> hotel.room.amenity
- hotel.room.amenities.type -> hotel.room.amenity.type
- hotel.services -> hotel.service

Fields to rename:

- **order_line_id** (instead of service_line_id) for hotel.service.line many2one relation to sale.order.line: 
- **parent_id** (instead of amenity_id / categ_id / service_id) when models are relating to themselves (hotel.room.amenities.type, hotel_room_type, hotel_service_type)
- **product_manager_id** (instead of product_manager) relating to res.users (hotel.room, hotel.room.amenities, hotel.room.services)
- **type_id** (instead of room_categ_id, amenities_categ_id, service_categ_id) when they refer to their type (hotel.room, hotel.room.amenities, hotel.room.services).

@ShwetaSerpentCS @Rajan-SerpentCS @JayVora-SerpentCS @dhruvitaSerpentCS  @abdawone @mclaeysb   Any thoughts?

**Comment by norlinhenrik** [comment]
I will not continue with `hotel` migration to 16.0, because we are not going to use this module.

I leave the PR open so that someone else can benefit from the migration work that has been done so far.

**Comment by nikul-serpentcs** [comment]
Supersede https://github.com/OCA/vertical-hotel/pull/198

@JayVora-SerpentCS Please close this PR.

**Pull request closed without merging**
