### PR TITLE
[15.0][MIG]hotel_housekeeping

### PR DESCRIPTION
**Pull request by ShwetaSerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Can you please check if hotl itself is upgraded in v15?

**Comment by ShwetaSerpentCS** [comment]
@JayVora-SerpentCS 
Yes, Hotel itself is already upgraded.
Here it is a reference : https://github.com/OCA/vertical-hotel/pull/162

**Comment by ShwetaSerpentCS** [comment]
@JayVora-SerpentCS @murtuzasaleh This PR is ready for review.

**Comment by ShwetaSerpentCS** [comment]
> @JayVora-SerpentCS @murtuzasaleh This PR is ready for review.

@nikul-serpentcs

**Pull request merged**
