### PR TITLE
[12.0] setup pre-commit

### PR DESCRIPTION
**Pull request by robinkeunen**
Addes pre-commit to the repository and fixed the warnings. I'll squash the commits when the PR is approved.

### CODE REVIEW

**Comment by mclaeysb** [comment]
Thanks for all the work @robinkeunen !

There seem to be some references to `11.0` in some of the `.rst` file changes.
Please check 

`hotel/README.rst`
`hotel_housekeeping/readme/DESCRIPTION.rst`
`hotel_reservation/readme/DESCRIPTION.rst`
`hotel_restaurant/README.rst`
`hotel_restaurant/readme/DESCRIPTION.rst`
`report_hotel_reservation/README.rst`

**Comment by robinkeunen** [comment]
Good one, I regenerated the rst files, rebased and pushed.

**Comment by JayVora-SerpentCS** [comment]
Squash please!

**Comment by robinkeunen** [comment]
Here you go :-)

**Review by JayVora-SerpentCS — APPROVED** [review]

**Review by vimalpatelserpentcs — APPROVED** [review]

**Pull request merged**
