### PR TITLE
[11.0][FIX]hotel:Fixed issue #51

### PR DESCRIPTION
**Pull request by dhruvitaSerpentCS**
#51

### CODE REVIEW

**Comment by dhruvitaSerpentCS** [comment]
@JayVora-SerpentCS  Can you please review and merge it? 
Thanks.

**Comment by JayVora-SerpentCS** [comment]
@dhruvitaSerpentCS We need to check:
- Why we have 2 categories?
- Isnt hotel.room.type using delegation?

**Comment by JayVora-SerpentCS** [comment]
Travis and runbot both needs be green.

**Comment by dhruvitaSerpentCS** [comment]
> @dhruvitaSerpentCS We need to check:
> 
> * Why we have 2 categories?
> * Isnt hotel.room.type using delegation?

Well!We have delegated hotel.room with product and in hotel.room model already have  categ_id fields which is separately managed with hotel room category model. so #51 issue is raised and second issue is (during the testing I have found), If we go with old flow then the price list feature is not working in category case,because hotel room category is not linked with product category.
So In this PR simply we have delegated hotel.room.category with product category (linked with product category), so existing flow works well.

**Comment by JayVora-SerpentCS** [comment]
Check a conflict please.

**Pull request closed without merging**
